### PR TITLE
Add support for scientific notation floats

### LINKED ISSUE #7: Parse floats
This is something that was skipped in the first version for simplicity but is crucial for any shader.

### PR DESCRIPTION
**Pull request by Kangz**
Fixes #7

### CODE REVIEW

**Comment by JCapucho** [comment]
It seems fine to me but I thought the plan moving forward would be to not lex so early on and instead to handle token pasting and then lex it later

**Comment by Kangz** [comment]
That's correct, but we need to build the string for the whole token, which this PR does. It just ends up calling Rust's `parse::<f32>` like was done previously.

**Comment by JCapucho** [comment]
Oh okay then, everything looks good so merge it if you want

**Comment by Kangz** [comment]
Thanks

**Pull request merged**
